### ISSUE TITLE
how to solve this bug?

### ISSUE THREAD

**Issue by etcshell** [driftyco/ionic-starter-super#101]
Runtime Error
Cannot find module "ionic-native"
Stack
Error: Cannot find module "ionic-native"
    at d (http://localhost:8100/build/polyfills.js:3:3991)
    at Object.<anonymous> (http://localhost:8100/build/main.js:78513:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:78182:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:117596:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10
Ionic Framework: 3.1.0
Ionic App Scripts: 1.3.5
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 7.4.0
OS Platform: OS X El Capitan
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWe

**Comment by gslender** [comment]
I've also seen this bug and gave up testing/trying to work with the Super-Starter template. A shame as I think I would have really appreciated having this resource work. Seem the technical goal posts in Ionic are shifting so quickly the supporting resources (docs/templates) aren't being kept up....

**Comment by gslender** [comment]
Oh and same as open bug #99

**Comment by devnetics** [comment]
You need to follow the upgrade path for Ionic 3. Several changes were made to imports, including Ionic-Native. Make sure you are importing ionic-native properly. Check the Readme:

https://github.com/driftyco/ionic-native/blob/master/README.md

For example:

`import { InAppBrowser } from 'ionic-native';`
Should now be ->
`import { InAppBrowser } from '@ionic-native/in-app-browser';`

**Comment by danielsogl** [comment]
Hey @etcshell, fixed with the next release.
