### ISSUE TITLE
Can't resolve all parameters for Storage: (?)

### ISSUE THREAD

**Issue by timofeysie** [driftyco/ionic-starter-super#102]
I am following the instructions on [this page](https://forum.ionicframework.com/t/guide-how-to-update-to-ionic-3-x/87516) for a [cloned super starter project](https://github.com/timofeysie/heat-wave) created a few months ago.

Here is the full stack trace:
```
Runtime Error
Can't resolve all parameters for Storage: (?).
Stack
Error: Can't resolve all parameters for Storage: (?).
    at d (http://localhost:8100/build/polyfills.js:3:3991)
    at syntaxError (http://localhost:8100/build/main.js:100139:34)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:8100/build/main.js:112989:35)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:8100/build/main.js:112857:26)
    at CompileMetadataResolver._getInjectableMetadata (http://localhost:8100/build/main.js:112843:21)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:8100/build/main.js:113132:40)
    at http://localhost:8100/build/main.js:113062:49
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:8100/build/main.js:113023:19)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/main.js:112678:50)
    at JitCompiler._loadModules (http://localhost:8100/build/main.js:123770:64)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/main.js:123729:52)
    at JitCompiler.compileModuleAsync (http://localhost:8100/build/main.js:123691:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:8100/build/main.js:5064:25)
    at PlatformRef_.bootstrapModule (http://localhost:8100/build/main.js:5050:21)
Ionic Framework: 3.1.1
Ionic Native: 2.4.1
Ionic App Scripts: 1.3.6
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 6.9.2
OS Platform: OS X Yosemite
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
```
I was dealing with a runtime error regarding the TranslateHttpLoader.
There is an [open issue on their repo](https://github.com/driftyco/ionic-starter-super/issues/98).
*ng2-translate is Angular 2, ngx-translate is Angular 4+ and Ionic 3+
The name is changed to deal with version break and semver from 5.0.0 to 6.0.1
ng2-translate 5 will fail with npm complaints for the ionic upgrade
Ref: #95 and other items that are related to this.*

The last issue there recommends changing the helper function:
```
return new TranslateStaticLoader(http, './assets/i18n', '.json');
```
Instead of the static loader we should use this: TranslateHttpLoader
However, this causes a red squiggly with the mouseover:
```
[ts] Cannot find name 'TranslateHttpLoader'.
```

**Comment by devnetics** [comment]
@timofeysie Did you look at the following recently closed issue?

https://github.com/driftyco/ionic-starter-super/issues/81

Make sure you have the changes shown here:

https://github.com/driftyco/ionic-starter-super/pull/82/files

**Comment by timofeysie** [comment]
Notes on issue #81 state state this starter is *not quite production ready with this repo yet*

After applying the fix from [this](https://github.com/driftyco/ionic-starter-super/pull/82/files) commit which uses both Storage and IonicStorageModule, I am getting the following error:
```
_reportError — compiler.es5.js:14582Error: Can't resolve all parameters for TutorialPage: ([object Object], [object Object], [object Object], ?).
```
Should I open a separate issue for this error?

**Comment by geeballer** [comment]
@danielsogl  mind ask why this was closed. I;m having the similar issue which  @timofeysie commented  . Kindly revert. thanks
