### ISSUE TITLE
Runtime Error if clicked directly on settings icon

### ISSUE THREAD

**Issue by john5db** [driftyco/ionic-starter-super#57]
On first ionic serve if i click directly on settings icon it produces following error.
```
Runtime Error
Uncaught (in promise): TypeError: Cannot read property 'option1' of undefined TypeError: Cannot read property 'option1' of undefined at SettingsPage._buildForm 
(http://localhost:8100/build/main.js:38413:35) at http://localhost:8100/build/main.js:38444:19 at t.invoke (http://localhost:8100/build/polyfills.js:3:9094) at Object.onInvoke
 (http://localhost:8100/build/main.js:35915:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:9045) at e.run (http://localhost:8100/build/polyfills.js:3:6481) at 
http://localhost:8100/build/polyfills.js:3:4583 at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723) at Object.onInvokeTask 
(http://localhost:8100/build/main.js:35906:37) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)

```
if i close that error it works fine.

Screen shot of error
![tt](https://cloud.githubusercontent.com/assets/11294840/21621181/dfdb5724-d21d-11e6-9bca-47faafeb3aea.jpg)

**Comment by clodo** [comment]
Hi @john5db,
I think the error is fixed [here](https://github.com/driftyco/ionic-starter-super/issues/14).
I hope this helps

**Comment by wbhob** [comment]
Can this be closed?
