### ISSUE TITLE
Runtime Error Cannot find module "ionic-native"

### ISSUE THREAD

**Issue by HaidarZ** [driftyco/ionic-starter-super#97]
It seems that the starter build failed,when I run `ionic serve` the following error occured
```
Runtime Error
Cannot find module "ionic-native"
Stack
Error: Cannot find module "ionic-native"
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at Object.<anonymous> (http://localhost:8100/build/main.js:108352:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:82204:73)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:120594:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10
```

`Ionic Framework: 3.0.1
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 6.10.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36`

**Comment by ietuday** [comment]
I am also getting same Error. How you solved it????

Help....

**Comment by aebla84** [comment]
I think that its broke ... :S 
https://forum.ionicframework.com/t/cannot-find-module-ionic-native-with-ionic2-super-starter/87258/3
